### ISSUE TITLE
数据导入服务端优化

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3030]
同时处理以下相关任务（未处理）统一合并到本任务：

- [ ] 数据导入完成后，公式类型字段不会自动计算
- [ ] 数据导入很慢, 导入1200条只有name字段的数据,耗时4分钟 #3013
- [x] 导入数据时, 如果上传的附件不是excel类型, 则会导致整个服务停止 #3012
- [x] 对象数据导入后，错误日志使用html字段markdown展示 #2113
- [x] 数据导入：当字段类型为选择框时，数据类型 为复选框或数值时是否正常？ #3043
- [x] 相关表name字段都是数字情况下，数据导入失败 #2826

**Comment by sunhaolin** [comment]
- [ ] 新建数据导入报错 `Error: runFormula:Catch an error "Syntax error." while eval formula "," with params: "{}" for "undefined"`

**Comment by hotlong** [comment]
数据导入完成后，公式类型字段不会自动计算，可以点重算按钮。
