### ISSUE TITLE
国际化问题清单

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3441]
### 影响普通用户使用的需要国际化的功能：

- [x] 内置的字段分组“通用”和“系统信息”未能被国际化翻译 #3444
- [x] 选择框类型字段选项值如何设置国际化；【已入文档】
- [x] 应用及应用介绍如何国际化；【已入文档】
- [x] 列表视图名称

<img width="387" alt="image" src="https://user-images.githubusercontent.com/6219465/180901051-6874e4ba-424e-4264-8700-22f026660610.png">

- [x] 新版列表右侧的过滤器
![image](https://user-images.githubusercontent.com/6219465/180912955-b0563a6f-2b9d-4dd2-977e-5fb9a63b6034.png)

### 可以延后处理的设置界面相关国际化功能

- [x] 设置菜单国际化【已入文档，部分菜单未添加国际化变量，需要改源码加上】

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/174252181-8b6b0d4f-872c-4e5a-86dd-a99d80ab4b05.png">

- [ ] 字段设置页面布局分组后，分组名称如何国际化 #3443
- [ ] 选项卡如何实现国际化 #3448
- [ ] 权限集&简档如何国际化 #3453
- [ ] 表单验证消息，比如字段必填，邮件格式等未支持国际化 #3451
- [ ] 对象验证规则错误消息如何国际化 #3449
- [ ] 审批王-功能箱中，文件的发起时间提示为英文 ，公司平台2.2.36 #3408
- [x] amis 国际化打包英文

**Comment by yinlianghui** [comment]
关联issue已经直接关闭了，后续相关问题处理后直接在本issue中打勾跟进状态。

**Comment by hotlong** [comment]
遗留任务不处理
