### ISSUE TITLE
排除项目模版 npm 安装警告

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3569]
- [ ] request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
- [ ] querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
- [ ] debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
- [x] superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
- [x] steedos-server > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
- [ ] @steedos/license > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
- [ ] mssql > tedious > adal-node > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
- [ ] steedos-cli > request > har-validator@5.1.5: this library is no longer supported
- [ ] @steedos/objectql > moleculer-apollo-server > graphql-tools@7.0.5: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
- [ ]  @steedos/objectql > moleculer-apollo-server > apollo-server-core > graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
- [ ]  @steedos/accounts > mongoose > @types/mongodb > @types/bson@4.2.0: This is a stub types definition. bson provides its own type definitions, so you do not need this installed.
- [ ] bcrypt > node-pre-gyp@0.12.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
- [ ] @steedos/i18n > i18next-xhr-backend@3.2.2: replaced by i18next-http-backend
- [ ]  @steedos/meteor-bundle-dependencies > node-gcm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
- [ ]  @steedos/meteor-bundle-dependencies > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
- [ ] steedos-server > meteor-node-stubs > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
- [ ] steedos-server > socket.io > engine.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
- [ ] steedos-server > socket.io > socket.io-parser > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
- [ ] @steedos/objectql > moleculer-apollo-server > apollo-server-core > apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
- [ ]  @steedos/objectql > moleculer-apollo-server > apollo-server-core > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
- [ ]  @steedos/objectql > moleculer-apollo-server > apollo-server-core > apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
- [ ] @steedos/objectql > moleculer-apollo-server > apollo-server-core > graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
- [ ] @steedos/objectql > moleculer-apollo-server > graphql-tools > @graphql-tools/url-loader > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
- [ ] @steedos/objectql > moleculer-apollo-server > @hapi/accept > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
- [ ] @steedos/objectql > moleculer-apollo-server > @hapi/accept > @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
- [ ]  @steedos/service-api > moleculer-apollo-server > graphql-tools > @graphql-tools/url-loader > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
- [ ] @steedos/service-api > graphql-iso-date@3.6.1" has incorrect peer dependency "graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".

**Comment by hotlong** [comment]
request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
