### ISSUE TITLE
审批王，增加支持QHD公文的部分原有机制

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4322]
一、基于原有表单模板
- [x] 审批单框表之外，部分div（例如下图中的收文日期、所属部门）无width 、导致 实际居左了（虽然div为 居右）https://github.com/steedos/steedos-project-hbport/issues/34
- [x] 表头（如收文处理单），下拉框右侧的“倒三角”点击无作用
https://github.com/steedos/steedos-project-hbport/issues/31

二、基于原有相关事件（脚本）
- [x] 原有日期控件需增加支持， https://github.com/steedos/steedos-project-hbport/issues/32 ； https://github.com/steedos/steedos-project-hbport/issues/44 

三、基于原有表单脚本

- [x] 脚本不适用导致附件 显示为 办理结果  https://github.com/steedos/steedos-project-hbport/issues/35

脚本：
$(".btn-instance-update").on('instance-before-save', function(e) {
var current_step = InstanceManager.getCurrentStep();
Meteor.call('check_main_attach', Session.get('instanceId'), '办理结果', function(err, result) { console.log(result) })
});

四、其他

- [x] 日期/时间/下拉类型字段，即便没有编辑权限，也会显示倒三角 https://github.com/steedos/steedos-project-hbport/issues/34
- [x] 日期/时间类型字段，显示高度比之前要高 https://github.com/steedos/steedos-project-hbport/issues/34

**Comment by marchtian** [comment]
https://github.com/steedos/steedos-platform/issues/4362

**Comment by marchtian** [comment]
0224/26 42.46 上测试确认，上述问题，已从 流程机制 改进，此后无需据此调整 流程的相关设置
