### ISSUE TITLE
[Task]: cms知识列表优化

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5414]
### SubTasks 子任务（廖处理）

- [x] 左侧头像对齐
- [x] 站点、栏目支持排序
- [x] 站点、栏目、知识表单排版（配置字段先后顺序）
- [x] 站点成员，括号（私有）去掉
- [x] 站点封面等字段去掉（注释掉）
- [x] 默认配置几个过滤字段，即设置搜索项中不应该一个字段都没有
- [x] 左侧选中效果（找涂讨论技术问题）
- [x] 文章表单中文章级权限联动效果，只有勾选文章级权限时才显示下面的发布对象字段
- [x] 附件子表功能，不使用附件字段

### 其他问题先建issue后续单独处理

- 左侧站点列表支持拖拉排序 #5415
- 知识预览支持显示附件列表 #5416
- 附件和图片匿名访问问题 #5417
- 正文（html字段类型），要支持搜索，搜索时显示为一个普通文本框 #5418

**Comment by Flyingliao** [comment]
- [ ] 左侧头像对齐。     处理方案： 左侧根节点无子分支显示头像，有分支显示下拉箭头
