### ISSUE TITLE
[Task]: amis升级到3.6.3

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6039]
### SubTasks 子任务

- [x] 列表单元格编辑和批量编辑功能及样式异常【涂】
![image](https://github.com/steedos/steedos-platform/assets/6219465/8c0edb16-71c6-49ee-9ff8-0fe784a9ed06)

- [x] 审批王左侧树样式异常【廖】
![image](https://github.com/steedos/steedos-platform/assets/6219465/7883cf61-009f-4d5d-b260-223ab79deca6)

- [x] 审批王新建草稿窗口，选中流程新建草稿时报错功能异常【廖】
![image](https://github.com/steedos/steedos-platform/assets/6219465/05012869-5db4-4c71-8585-d3b03e7704c7)

- [x] 日程对象日历视图，画布中拖动选择范围新建日程记录时，弹出的是人员表单【涂】
![image](https://github.com/steedos/steedos-platform/assets/6219465/2cc33f68-3663-4872-964b-94f5d9cdeac8)

- [x] lookup字段编辑模式显示了滚动条【廖】
![image](https://github.com/steedos/steedos-platform/assets/6219465/84bf0071-f04b-46e3-b096-66e24044a58e)

- [x] 新版子表组件列表最后操作列按钮宽度显示异常【殷，功能测试下来好像比较完美，没发现其他bug】
![image](https://github.com/steedos/steedos-platform/assets/6219465/1ee0e34a-0691-4d54-853e-a8c2de8808d9)

- [ ] 列表搜索功能有些操作会报错，lookup字段有时显示成id未显示label【殷】
![image](https://github.com/steedos/steedos-platform/assets/6219465/f42d234a-6bf6-4110-90df-8708956af9e1)
此问题跟amis 3.6没关系，是统一的bug，单独建issue了：[Bug]: 列表搜索表单有时出现lookup字段显示为id而不是label的情况，刷新浏览器后又好了 https://github.com/steedos/steedos-platform/issues/6043

**Comment by Flyingliao** [comment]
树对象列表视图下展开异常：
 <img width="987" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/fdf44ab0-c064-4e4c-97ad-9fda43d81616">

**Comment by baozhoutao** [comment]
新建合同报错: broadcast 动作执行失败，原因：reload 动作执行失败，原因：[mobx-state-tree] Cannot modify 'frozen[]@/selectedItems [dead]', the object is protected and can only be modified by using an action.
![image](https://github.com/steedos/steedos-platform/assets/6194462/96adfaf2-63dc-4352-bd23-4047593ccb3c)

**Comment by baozhoutao** [comment]
流程字段显示报错
<img width="1157" alt="image" src="https://github.com/steedos/steedos-platform/assets/6194462/0ececc7e-012d-4dc1-ab0a-af2424fb90bf">

**Comment by baozhoutao** [comment]
流程表单显示报错:
<img width="1134" alt="image" src="https://github.com/steedos/steedos-platform/assets/6194462/f7b605ee-8748-4390-8333-b61a73d33223">

**Comment by yinlianghui** [comment]
- [ ] lookup字段弹出窗口报错，且选项列表中数据明显少了。

![image](https://github.com/steedos/steedos-platform/assets/6219465/2ba8b751-e3bc-4a42-9990-b81f4b9a4064)

**Comment by yinlianghui** [comment]
- [ ] lookup字段弹出列表窗口中点击新建按钮，点击保存报错，比如指向项目集的lookup字段。【廖】

![image](https://github.com/steedos/steedos-platform/assets/6219465/b20f724c-159d-4094-b82c-faa3917e0590)

![image](https://github.com/steedos/steedos-platform/assets/6219465/7bcd4942-d363-43ec-baf3-a983221df03f)

**Comment by yinlianghui** [comment]
- [ ] 记录详细页面子表列表全是坏的
![image](https://github.com/steedos/steedos-platform/assets/6219465/31847305-60ad-4a69-8614-c66e366c1067)

**Comment by tujiajun** [comment]
- [ ] 手机端标题显示异常
![image](https://github.com/steedos/steedos-platform/assets/127007861/88260a8f-6ed6-4746-88e6-ce7cb6397944)

**Comment by Flyingliao** [comment]
- [ ] 子表列名消失不见、表头尾部最后一个单元格样式异常
<img width="1115" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/35e93bc1-5894-4dac-bc31-033ba05ab3df">

**Comment by yinlianghui** [comment]
- [ ] 项目详细页面相关子表中的里程碑列表新建记录弹出的表单中，点击责任人字段弹出列表时报错（如果主表，即项目记录的项目成员有值不会报错，且只有amis 3.6才有这个问题，3.2是好的）

![image](https://github.com/steedos/steedos-platform/assets/6219465/05b2963b-1fa0-4a98-8d3f-bbbb58d5c65a)

**Comment by yinlianghui** [comment]
- [ ] [Bug]: 引用amis3.6时，点击列表顶部搜索表单的搜索按钮后底部空出一片灰色背景 #6051【殷，不严重，可以稍晚处理】

**Comment by Flyingliao** [comment]
- [ ] 附件子表不能上传附件
 
<img width="1213" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/ecb75689-5e59-4de8-a697-311e18a91575">

**Comment by tujiajun** [comment]
手机端下拉按钮点击报错
![image](https://github.com/steedos/steedos-platform/assets/127007861/7c97c66c-33c0-4cb5-9b7f-54010d38b91a)

**Comment by yinlianghui** [comment]
- [ ] 选部门字段（lookup树对象列表字段）左侧折叠按钮样式异常

![image](https://github.com/steedos/steedos-platform/assets/6219465/7c565c59-fe8f-460e-a407-2f83a48a465e)

**Comment by yinlianghui** [comment]
- [ ] 人员详细页面相关表中的“审批岗位成员“子表列表中审批岗位列显示为id值了，点击进去的详细页面是好的【廖】


![image](https://github.com/steedos/steedos-platform/assets/6219465/17deaaff-8f39-4636-8fb5-b6cbb6832a77)

**Comment by yinlianghui** [comment]
- [ ] 子表组件编辑行弹出窗口中lookup字段未显示label，且下拉选项为空

比如配置列表视图显示的列时，字段下拉列表为空
![image](https://github.com/steedos/steedos-platform/assets/6219465/9cf5e250-0dfc-4fd6-9543-4806e0bc78ea)

再比如工作流规则”时间触发器“子表，新建行时没问题，编辑行时有问题

![image](https://github.com/steedos/steedos-platform/assets/6219465/48f64cd6-c7f8-4629-94de-144d1ab158cf)

**Comment by Flyingliao** [comment]
- [ ] 设计器中：列表视图组件的视图属性选项中无用户自定义的视图
 
<img width="1242" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/8ec30142-aa95-4db3-bb34-677ca837e074">

**Comment by Flyingliao** [comment]
- [ ] 新建页面布局，字段菜单栏下的字段列未显示label
 
<img width="1090" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/023608ff-c088-44f4-a60f-e55e14bd7889">

**Comment by Flyingliao** [comment]
- [ ] 对象详情下的对象权限子表 中“权限集”未显示label。
 
<img width="1059" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/cef4e189-2a97-4338-ba8b-8e09a5e3adda">

**Comment by Flyingliao** [comment]
- [ ] 共享规则只读界面 “系统”字段不应该放在第一个位置
 
<img width="1021" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/914d9490-989c-4b9e-afb0-e6da98648679">

 - [ ] 共享规则编辑界面 “对象”字段无选项，未显示其label。
 
<img width="1060" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/b31d8f26-797c-4063-a90e-dba06f0fd9ee">

**Comment by yinlianghui** [comment]
审批列表名称字段链接颜色不对
![image](https://github.com/steedos/steedos-platform/assets/6219465/cfbe52a5-d66c-4433-81ae-2bbe7783cf13)

**Comment by tujiajun** [comment]
- [ ] 详细页宽度异常
![image](https://github.com/steedos/steedos-platform/assets/127007861/3f1d8b0c-1216-4479-94f2-6831d5467d59)
