### ISSUE TITLE
[Task]: 打印模板应用于列表页

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#6099]
### SubTasks 子任务

   - [ ] 如果是列表页，使用列表的查询条件过滤数据。最多不超过1000条。
   - [ ] 如果是列表页选中记录，使用 _id in [xxxx,yyy] 过滤记录。
   - [ ] 列表页，可以选中记录打印，也可以打印所有记录。最多不超过1000条。
   
   原始任务：[Feature]: 打印模版插件 @steedos-labs/print #5938
