### ISSUE TITLE
[Task]: 前台编辑应用菜单功能测试问题汇总

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#7017]
### SubTasks 子任务

- bug：
- [x] 用户页面，空分组应该不显示在页面上
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/ebf6cbcc-29fd-4eb2-9ec8-7a5ead3392cf">

- [x] 管理员应用页面，搜索框无效（用户页面正常搜索）
<img width="761" alt="image" src="https://github.com/user-attachments/assets/d5b95a89-fde4-47aa-9009-669f703d2bc8">

- [x] 对象上的编辑应该进入到当前的对象的设置页面，不是直接跳转到对象设计器
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/0d48b484-e28e-4901-b83c-fe2795276d51">

- [x] 管理员页面设置应用下，多出来两个空白分组
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/b059a1cc-bc1c-477a-909a-4899f34c5b54">

- [x] 九宫格应用，当超过9个应用时才显示更多按钮
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/141ed989-1ee3-47f5-aaf2-438573ca3ef2">

- [x] 新建应用时，唯一标识应该根据api规则自动赋值（设置中创建应用api也可以随便填，没有之前的api填写规则了）
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/7a8a35f5-29bc-4686-91c3-c05b914222ef">

- [x] 菜单不应该出现横向滚动条
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/b589f880-ca08-49d6-88e9-50465ea16d6f">

- [x] 设计器保存时没有校验字段的必填属性
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/bcbbfcbb-8c20-4df9-8a72-aab245424d41">

- [x] 设计器添加的人员相关表字段，列表页正常显示，但是详情页字段值出不来（默认字段放开显示以后，也是看不到值）
<img width="1119" alt="image" src="https://github.com/user-attachments/assets/8f06c9f0-97a9-4982-b6e8-ee0e56ccd1a0">
<img width="1730" alt="image" src="https://github.com/user-attachments/assets/c8e805d0-bbb6-46ba-a525-62c0f84f7095">

- [x] 字段没设置分组的时候，前台不显示这个字段
<img width="1316" alt="image" src="https://github.com/user-attachments/assets/48d8e1db-153b-4b6e-9821-6b3fd9d1d25b">
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/99253bc1-0ea5-4027-ac2c-40bb489ae12f">

- [x] 新建分组后，将标准字段拖进去，不好用，分组大小会跳来跳去

- 需要讨论：

- [x] 设计器中可以删除内核字段，但是保存后前台还是可以看到对应字段，有点奇怪，要讨论下这个怎么处理
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/8d216f32-3460-4c31-a8db-dc3b32545a15">

- [x] 设计器中名称字段可以删除，导致再未添加其他字段的情况下，前台新建页面是空白，并且可以成功保存
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/fd509674-426d-4910-98a2-6fdd12d05243">

- [ ] 我建议这些新建以后，都是浏览器打开新窗口，因为创建完成后，要一直点返回才能回到最开始的应用页面，很麻烦
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/cc3f4fda-f0ac-4ac6-a4bd-3fda0256c377">
